services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-backend
    ports:
      - "8080:8080"
    command: ["./gradlew", "run"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
