version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/todos.db:/app/todos.db
    environment:
      - DATABASE_URL=sqlite:///./todos.db

# Blocked request. This host ("ebiznes-2025-frontend.onrender.com") is not allowed.
# To allow this host, add "ebiznes-2025-frontend.onrender.com" to `server.allowedHosts` in vite.config.js.
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000